version: 2
updates:
  - package-ecosystem: "gradle"  # Specify Gradle as the package manager
    directory: "/"               # Root directory of your project
    schedule:
      interval: "weekly"          # Define how often Dependabot should check for updates
